version: '3.8'

services:
  postgres:
    image: "postgres"
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_management_system
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: